<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Workload;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // Seed users
        //0 = ไม่มี,ผู้ดูแลระบบ (ผู้ดูแลระบบ จะถูกยกเว้นจากการตรวจสอบระดับ rank จึงตั้งค่าพื้นฐานเป็น 0)
        //1 = เจ้าหน้าที่
        //2 = อาจารย์
        //3 = หัวหน้าหลักสูตร
        //4 = หัวหน้าสาขา
        //5 = ผู้ช่วยคณบดี
        //6 = รองคณบดี
        $users = [
            [
                'name' => 'Admin',
                'email' => 'admin@mail.com',
                'password' => Hash::make('123456'),
                'role' => 'admin',
                'rank' => '0',
            ],
            [
                'name' => 'Staff',
                'email' => 'staff@mail.com',
                'password' => Hash::make('123456'),
                'role' => 'user',
                'rank' => '1',
            ],
            [
                'name' => 'นายทดสอบ ระบบ 1',
                'email' => 'professor1@mail.com',
                'password' => Hash::make('123456'),
                'role' => 'user',
                'rank' => '2',
            ],
            [
                'name' => 'นายเทส ระบบ 2',
                'email' => 'professor2@mail.com',
                'password' => Hash::make('123456'),
                'role' => 'user',
                'rank' => '2',
            ],
        ];

        foreach ($users as $user) {
            User::factory()->create($user);
        }

        // Seed workloads
        $workloads = [
            'ภาระงานสอน',
            'ภาระงานวิจัยและงานวิชาการอื่นที่ปรากฏเป็นผลงานวิชาการตามหลักเกณฑ์ที่ ก.พ.อ กำหนด',
            'ภาระงานบริการทางวิชาการ',
            'ภาระงานทำนุบำรุงศิลปวัฒนธรรม',
            'ภาระงานอื่นๆ ที่สอดคล้องกับพันธกิจของคณะและมหาวิทยาลัย'
        ];

        foreach ($workloads as $workload) {
            Workload::create(['name' => $workload, 'description' => '']);
        }

        // Seed subworkloads
        DB::table('subworkloads')->insert([
            ['id' => 1, 'name' => '๑.๑ ภาระงานสอนทฤษฎีเฉพาะภาคปกติ', 'description' => NULL, 'workload_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'name' => '๑.๒ ภาระงานสอนปฏิบัติฉพาะภาคปกติ', 'description' => NULL, 'workload_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'name' => '๑.๓ การดูแลนักศึกษารายวิชาฝึกงาน สหกิจศึกษา ฝึกประสบการณ์วิชาชีพครู โครงการ และวิชาอื่นที่ไม่ปรากฏเวลาในตารางสอน', 'description' => NULL, 'workload_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4, 'name' => '๑.๔ ภาระงานการเป็นที่ปรึกษาปัญหา พิเศษวิชาโครงการ/โครงงาน (เพื่อสำเร็จ การศึกษา)/วิทยานิพนธ์ การศึกษาเฉพาะ เรื่อง สารนิพนธ์/การค้นคว้าอิสระ/ปริญญา นิพนธ์ ศิลปนิพนธ์ ', 'description' => NULL, 'workload_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 5, 'name' => '๑.๕ การจัดการเรียนการสอนโดยวิธีการอื่นๆ', 'description' => NULL, 'workload_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 6, 'name' => '๒.๑ เกณฑ์ภาระงานสําหรับการพัฒนาผลงานทางวิชาการเอกสารประกอบการสอน/ เอกสารคําสอน', 'description' => NULL, 'workload_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 7, 'name' => '๒.๒ เกณฑ์ภาระงานสำหรับการเขียนหนังสือ ตำรา และงานแปล', 'description' => NULL, 'workload_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 8, 'name' => '๒.๓ เกณฑ์การคิดภาระงานสำหรับการจัดทำข้อเสนอโครงการวิจัย', 'description' => NULL, 'workload_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 9, 'name' => '๒.๔ เกณฑ์การคิดภาระงานวิจัยโครงการเดี่ยว และโครงการย่อยในโครงการชุดวิจัย', 'description' => NULL, 'workload_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            // ['id' => 10, 'name' => '๒.๔ เกณฑ์การคิดภาระงานวิจัยโครงการเดี่ยว และโครงการย่อยในโครงการชุดวิจัย (งบประมาณการวิจัยจากหน่วยงานนอกมหาวิทยาลัย (ระดับชาติ และ นานาชาติ)', 'description' => NULL, 'workload_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 11, 'name' => '๒.๕ เกณฑ์การคิดภาระงานวิจัยของชุดโครงการวิจัย', 'description' => NULL, 'workload_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 12, 'name' => '๒.๖ เกณฑ์การคิดภาระงานสำหรับโครงการวิจัยร่วมที่ดำเนินการกับหน่วยงานภายนอก (โดยไม่ได้รับงบประมาณผ่านมหาวิทยาลัยและมีหนังสือราชการหน่วยงานภายนอกโดยผ่านหน่วยงานต้นสังกัดหรือมหาวิทยาลัย)', 'description' => NULL, 'workload_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 13, 'name' => '๒.๗ เกณฑ์การคิดภาระงานเผยแพร่ผลงานวิจัย ผลงานทางวิชาการ หรืองานสร้างสรรค์', 'description' => NULL, 'workload_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 14, 'name' => '๓.๑ เกณฑ์ภาระงานสำหรับการเป็นอาจารย์พิเศษ/วิทยากรของหน่วยงานภายนอก/ภายใน หรือกรรมการอื่น ๆ', 'description' => NULL, 'workload_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 15, 'name' => '๓.๒ เกณฑ์การคิดภาระงานการจัดประชุม สัมมนาฝึกอบรมและจัดนิทรรศการ', 'description' => NULL, 'workload_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 16, 'name' => '๓.๓ การสัมมนา การประชุมวิชาการ', 'description' => NULL, 'workload_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 17, 'name' => '๓.๔ เกณฑ์การคิดภาระงานที่ปรึกษาโครงการจับวิทยานิพนธ์/เมธีวิจัย/ผู้เชี่ยวขาญ', 'description' => NULL, 'workload_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 18, 'name' => '๓.๕ เกณฑ์การคิดภาระงานสำหรับงานที่มีรายได้เข้ามหาวิทยาลัย', 'description' => NULL, 'workload_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 19, 'name' => '๔.๑ เกณฑ์การคิดภารศึกษางานการจัดโครงการทำนุบำนุบำรุงศิลปะ วัฒนธรรม', 'description' => NULL, 'workload_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 20, 'name' => '๔.๒ เกณฑ์การคิดภาระงานการเข้าร่วมโครงการทำนุบำรุงศิลปะวัฒนะวัฒนธรรม', 'description' => NULL, 'workload_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 21, 'name' => '๕.๑ เกณฑ์การคิดภาระงานในลักษณะกิจกรรมที่เกี่ยวกับการเรียนการสอน งานบริการ วิชาการ/กิจกรรมนักศึกษา', 'description' => NULL, 'workload_id' => 5, 'created_at' => now(), 'updated_at' => now()],
        ]);

        // Seed list_subworkloads
        // หัวข้อ 1
        DB::table('list_subworkloads')->insert([
            ['id' => 1, 'name' => '๑. ระดับปริญญาตรี /ปวส./ปวช./อนุปริญญา (หลักสูตรภาษาไทย)', 'description' => NULL, 'subworkload_id' => 1, 'factor' => 0.00, 'sort_order' => 1, 'created_at' => now(), 'updated_at' => now(), 'is_child' => 1, 'list_subworkloads_child_id' => NULL],
            ['id' => 2, 'name' => '๒. ระดับปริญญาตรี /ปวส./ปวช./อนุปริญญา (หลักสูตรนานาชาติ (English Program))', 'description' => NULL, 'subworkload_id' => 1, 'factor' => 3.00, 'sort_order' => 1, 'created_at' => now(), 'updated_at' => now(), 'is_child' => 0, 'list_subworkloads_child_id' => NULL],
            ['id' => 3, 'name' => '๓. ระดับบัณฑิตศึกษา (หลักสูตรภาษาไทย)', 'description' => NULL, 'subworkload_id' => 1, 'factor' => 3.00, 'sort_order' => 1, 'created_at' => now(), 'updated_at' => now(), 'is_child' => 0, 'list_subworkloads_child_id' => NULL],
            ['id' => 4, 'name' => '๔. ระดับบัณฑิตศึกษา (หลักสูตรนานาชาติ)', 'description' => NULL, 'subworkload_id' => 1, 'factor' => 3.00, 'sort_order' => 1, 'created_at' => now(), 'updated_at' => now(), 'is_child' => 0, 'list_subworkloads_child_id' => NULL],
            ['id' => 5, 'name' => '๕. โครงการพิเศษทางบูรณาการของมหาวิทยาลัยทุกระดับ', 'description' => NULL, 'subworkload_id' => 1, 'factor' => 3.00, 'sort_order' => 1, 'created_at' => now(), 'updated_at' => now(), 'is_child' => 0, 'list_subworkloads_child_id' => NULL],
            ['id' => 6, 'name' => 'ภาระงานสอนปฏิบัติ ทุกระดับ/ทุกประเภท', 'description' => NULL, 'subworkload_id' => 2, 'factor' => 1.00, 'sort_order' => 1, 'created_at' => now(), 'updated_at' => now(), 'is_child' => 0, 'list_subworkloads_child_id' => NULL],
            ['id' => 7, 'name' => '๑.๑ จำนวนนักศึกษาต่อหนึ่งห้องเรียนน้อยกว่า ๓๐ คน', 'description' => NULL, 'subworkload_id' => 1, 'factor' => 2.00, 'sort_order' => 1, 'created_at' => now(), 'updated_at' => now(), 'is_child' => 0, 'list_subworkloads_child_id' => 1],
            ['id' => 8, 'name' => '๑.๒ จำนวนบักศึกษาต่อหนึ่งห้องเรียน ๓๐ - ๖๐ คน', 'description' => NULL, 'subworkload_id' => 1, 'factor' => 3.00, 'sort_order' => 1, 'created_at' => now(), 'updated_at' => now(), 'is_child' => 0, 'list_subworkloads_child_id' => 1],
            ['id' => 9, 'name' => '๑.๓ จำนวนบักศึกษาต่อหนึ่งห้องเรียนมากกว่า ๖๐ คน', 'description' => NULL, 'subworkload_id' => 1, 'factor' => 4.00, 'sort_order' => 1, 'created_at' => now(), 'updated_at' => now(), 'is_child' => 0, 'list_subworkloads_child_id' => 1],
            ['id' => 10, 'name' => 'นิเทศและประเมินผลการฝึกงาน/สหกิจศึกษา/การฝึกสอน (ต่อครั้ง) (นับได้ไม่เกิน 4 ครั้ง)', 'description' => NULL, 'subworkload_id' => 3, 'factor' => 1.00, 'sort_order' => 1, 'created_at' => now(), 'updated_at' => now(), 'is_child' => 0, 'list_subworkloads_child_id' => NULL],
            ['id' => 11, 'name' => 'ผู้ประสานงาน (ผู้รับผิดชอบรายวิชา)', 'description' => NULL, 'subworkload_id' => 3, 'factor' => 3.00, 'sort_order' => 1, 'created_at' => now(), 'updated_at' => now(), 'is_child' => 0, 'list_subworkloads_child_id' => NULL],
            ['id' => 12, 'name' => 'ปวช. (นับได้ไม่เกิน 3 เรื่อง)', 'description' => NULL, 'subworkload_id' => 4, 'factor' => 2.00, 'sort_order' => 1, 'created_at' => now(), 'updated_at' => now(), 'is_child' => 0, 'list_subworkloads_child_id' => NULL],
            ['id' => 13, 'name' => 'ปวส. (นับได้ไม่เกิน 3 เรื่อง)', 'description' => NULL, 'subworkload_id' => 4, 'factor' => 2.00, 'sort_order' => 1, 'created_at' => now(), 'updated_at' => now(), 'is_child' => 0, 'list_subworkloads_child_id' => NULL],
            ['id' => 14, 'name' => 'ปริญญาตรี (นับได้ไม่เกิน 5 เรื่อง)', 'description' => NULL, 'subworkload_id' => 4, 'factor' => 2.00, 'sort_order' => 1, 'created_at' => now(), 'updated_at' => now(), 'is_child' => 0, 'list_subworkloads_child_id' => NULL],
            ['id' => 15, 'name' => 'ปริญญาโท (ให้เป็นไปตามหลักเกณฑ์มาตรฐานบัณฑิตศึกษา)', 'description' => NULL, 'subworkload_id' => 4, 'factor' => 8.00, 'sort_order' => 1, 'created_at' => now(), 'updated_at' => now(), 'is_child' => 0, 'list_subworkloads_child_id' => NULL],
            ['id' => 16, 'name' => 'ปริญญาเอก (ให้เป็นไปตามหลักเกณฑ์มาตรฐานบัณฑิตศึกษา)', 'description' => NULL, 'subworkload_id' => 4, 'factor' => 12.00, 'sort_order' => 1, 'created_at' => now(), 'updated_at' => now(), 'is_child' => 0, 'list_subworkloads_child_id' => NULL],
            ['id' => 17, 'name' => 'การทัศนศึกษา/ศึกษาดูงานที่ปรากฏในคำอธิบายรายวิชา ชั่วโมง/โครงการ (คิดไม่เกิน ๓ โครงการ)', 'description' => NULL, 'subworkload_id' => 5, 'factor' => 1.00, 'sort_order' => 1, 'created_at' => now(), 'updated_at' => now(), 'is_child' => 0, 'list_subworkloads_child_id' => NULL],
        ]);

        // หัวข้อ 2
        DB::table('list_subworkloads')->insert([
            // 2.1
            [
                'id' => 18,
                'name' => '๑. สัดส่วนผลงานคิดได้ร้อยละ ๑๐๐ (ได้รับผลการประเมินการสอน)',
                'description' => NULL,
                'subworkload_id' => 6,
                'factor' => 4.00,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 19,
                'name' => '๒. สัดส่วนผลงานคิดได้ร้อยละ ๗๕ (ขอรับการประเมินการสอน)',
                'description' => NULL,
                'subworkload_id' => 6,
                'factor' => 3.00,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 20,
                'name' => '๓. สัดส่วนผลงานคิดได้ร้อยละ ๕๐ (มีรายชื่อบทความ/หนังสืออ่านประกอบ/แผนภูมิ/ ภาพเคลื่อนไหว/กรณีศึกษาและการอ้างอิงที่มา)',
                'description' => NULL,
                'subworkload_id' => 6,
                'factor' => 2.00,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 21,
                'name' => '๔. สัดส่วนผลงานคิดได้ร้อยละ ๒๕ (มีแผนการสอน หัวข้อบรรยาย (มีรายละเอียดพอสมควร) ตาม คําอธิบายรายวิชา)',
                'description' => NULL,
                'subworkload_id' => 6,
                'factor' => 1.00,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            // 2.2
            [
                'id' => 22,
                'name' => '๑. สัดส่วนผลงานใหม่คิดได้ร้อยละ ๑๐๐ ของผลงาน (เผยแพร่ตามเกณฑ์ ก.พ.อ.)',
                'description' => NULL,
                'subworkload_id' => 7,
                'factor' => 16.00,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 23,
                'name' => '๒. สัดส่วนผลงานใหม่คิดได้ร้อยละ ๗๕ ของผลงาน (ขอรับการประเมินคุณภาพผลงาน (Peer Review) (ภายใน คณะหรือสํานักพิมพ์)',
                'description' => NULL,
                'subworkload_id' => 7,
                'factor' => 12.00,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 24,
                'name' => '๓. สัดส่วนผลงานใหม่คิดได้ร้อยละ ๕๐ ของผลงาน (มีสารบัญ เนื้อเรื่อง การวิเคราะห์ การสรุป การอ้างอิง บรรณานุกรม ดัชนีค้นคําอย่างน้อย ๕ บท หรือ ๘๐ หน้า)',
                'description' => NULL,
                'subworkload_id' => 7,
                'factor' => 8.00,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 25,
                'name' => '๔. สัดส่วนผลงานใหม่คิดได้ร้อยละ ๒๕ ของผลงาน (มีสารบัญ เนื้อเรื่อง การวิเคราะห์ การสรุป การอ้างอิง บรรณานุกรมอย่างน้อย ๒ บท)',
                'description' => NULL,
                'subworkload_id' => 7,
                'factor' => 4.00,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            // 2.3
            [
                'id' => 26,
                'name' => '๑. จัดทำข้อเสนอโครงการวิจัยโครงการเดี่ยว (ต่อเรื่อง)',
                'description' => NULL,
                'subworkload_id' => 8,
                'factor' => 1.00,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 27,
                'name' => '๒. จัดทำข้อเสนอโครงการวิจัยชุด โครงการหลัก (ต่อเรื่อง)',
                'description' => NULL,
                'subworkload_id' => 8,
                'factor' => 1.00,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 28,
                'name' => '๓. จัดทำข้อเสนอโครงการวิจัยชุด โครงการย่อย (ต่อเรื่อง)',
                'description' => NULL,
                'subworkload_id' => 8,
                'factor' => 1.00,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            // 2.4 ในประเทศ + หัวหน้า
            [
                'id' => 29,
                'name' => '๑.๑  ไม่ใช้งบประมาณ โดยผ่านความเห็นชอบจาก การวิจัย คณะ/วิทยาลัย',
                'description' => NULL,
                'subworkload_id' => 9,
                'factor' => 3.00,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 30,
                'name' => '๑.๒ ไม่ถึง ๑๐๐,๐๐๐ บาท',
                'description' => NULL,
                'subworkload_id' => 9,
                'factor' => 6.00,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 31,
                'name' => '๑.๓ ๑๐๐,๐๐๐ - ๕๐๐,๐๐๐ บาท',
                'description' => NULL,
                'subworkload_id' => 9,
                'factor' => 7.00,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 32,
                'name' => '๑.๔ ๕๐๐,๐๐๐ - ๑,๐๐๐,๐๐๐ บาท',
                'description' => NULL,
                'subworkload_id' => 9,
                'factor' => 8.00,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 33,
                'name' => '๑.๕ ๑,๐๐๐,๐๐๐ - ๓,๐๐๐,๐๐๐ บาท',
                'description' => NULL,
                'subworkload_id' => 9,
                'factor' => 10.00,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 34,
                'name' => '๑.๖  มากกว่า ๓,๐๐๐,๐๐๐ บาท',
                'description' => NULL,
                'subworkload_id' => 9,
                'factor' => 12.00,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            // 2.4 ในประเทศ + ผู้ร่วม
            [
                'id' => 35,
                'name' => '๑.  ไม่ใช้งบประมาณ โดยผ่านความเห็นชอบจาก การวิจัย คณะ/วิทยาลัย',
                'description' => NULL,
                'subworkload_id' => 9,
                'factor' => 3.00,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 36,
                'name' => '๒. ไม่ถึง ๑๐๐,๐๐๐ บาท',
                'description' => NULL,
                'subworkload_id' => 9,
                'factor' => 3.00,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 37,
                'name' => '๓. ๑๐๐,๐๐๐ - ๕๐๐,๐๐๐ บาท',
                'description' => NULL,
                'subworkload_id' => 9,
                'factor' => 3.00,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 38,
                'name' => '๔. ๕๐๐,๐๐๐ - ๑,๐๐๐,๐๐๐ บาท',
                'description' => NULL,
                'subworkload_id' => 9,
                'factor' => 3.00,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 39,
                'name' => '๕. ๑,๐๐๐,๐๐๐ - ๓,๐๐๐,๐๐๐ บาท',
                'description' => NULL,
                'subworkload_id' => 9,
                'factor' => 3.00,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 40,
                'name' => '๖.  มากกว่า ๓,๐๐๐,๐๐๐ บาท',
                'description' => NULL,
                'subworkload_id' => 9,
                'factor' => 3.00,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            // // 2.4 ต่างประเทศ + หัวหน้า
            // [
            //     'id' => 41,
            //     'name' => '๑.๑  ไม่ใช้งบประมาณ โดยผ่านความเห็นชอบจาก การวิจัย คณะ/วิทยาลัย',
            //     'description' => NULL,
            //     'subworkload_id' => 9,
            //     'factor' => 6.00,
            //     'sort_order' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'is_child' => 0,
            //     'is_unique' => 1,
            //     'is_leader' => 1,
            //     'is_country' => 1,
            //     'list_subworkloads_child_id' => NULL
            // ],
            // [
            //     'id' => 42,
            //     'name' => '๑.๒ ไม่ถึง ๑๐๐,๐๐๐ บาท',
            //     'description' => NULL,
            //     'subworkload_id' => 9,
            //     'factor' => 12.00,
            //     'sort_order' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'is_child' => 0,
            //     'is_unique' => 1,
            //     'is_leader' => 1,
            //     'is_country' => 1,
            //     'list_subworkloads_child_id' => NULL
            // ],
            // [
            //     'id' => 43,
            //     'name' => '๑.๓ ๑๐๐,๐๐๐ - ๕๐๐,๐๐๐ บาท',
            //     'description' => NULL,
            //     'subworkload_id' => 9,
            //     'factor' => 14.00,
            //     'sort_order' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'is_child' => 0,
            //     'is_unique' => 1,
            //     'is_leader' => 1,
            //     'is_country' => 1,
            //     'list_subworkloads_child_id' => NULL
            // ],
            // [
            //     'id' => 44,
            //     'name' => '๑.๔ ๕๐๐,๐๐๐ - ๑,๐๐๐,๐๐๐ บาท',
            //     'description' => NULL,
            //     'subworkload_id' => 9,
            //     'factor' => 18.00,
            //     'sort_order' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'is_child' => 0,
            //     'is_unique' => 1,
            //     'is_leader' => 1,
            //     'is_country' => 1,
            //     'list_subworkloads_child_id' => NULL
            // ],
            // [
            //     'id' => 45,
            //     'name' => '๑.๕ ๑,๐๐๐,๐๐๐ - ๓,๐๐๐,๐๐๐ บาท',
            //     'description' => NULL,
            //     'subworkload_id' => 9,
            //     'factor' => 20.00,
            //     'sort_order' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'is_child' => 0,
            //     'is_unique' => 1,
            //     'is_leader' => 1,
            //     'is_country' => 1,
            //     'list_subworkloads_child_id' => NULL
            // ],
            // [
            //     'id' => 46,
            //     'name' => '๑.๖  มากกว่า ๓,๐๐๐,๐๐๐ บาท',
            //     'description' => NULL,
            //     'subworkload_id' => 9,
            //     'factor' => 24.00,
            //     'sort_order' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'is_child' => 0,
            //     'is_unique' => 1,
            //     'is_leader' => 1,
            //     'is_country' => 1,
            //     'list_subworkloads_child_id' => NULL
            // ],
            // // ต่างประเทศ + ผู้ร่วม
            // [
            //     'id' => 47,
            //     'name' => '๑.๑  ไม่ใช้งบประมาณ โดยผ่านความเห็นชอบจาก การวิจัย คณะ/วิทยาลัย',
            //     'description' => NULL,
            //     'subworkload_id' => 9,
            //     'factor' => 6.00,
            //     'sort_order' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'is_child' => 0,
            //     'is_unique' => 1,
            //     'is_leader' => 1,
            //     'is_country' => 1,
            //     'list_subworkloads_child_id' => NULL
            // ],
            // [
            //     'id' => 48,
            //     'name' => '๑.๒ ไม่ถึง ๑๐๐,๐๐๐ บาท',
            //     'description' => NULL,
            //     'subworkload_id' => 9,
            //     'factor' => 6.00,
            //     'sort_order' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'is_child' => 0,
            //     'is_unique' => 1,
            //     'is_leader' => 1,
            //     'is_country' => 1,
            //     'list_subworkloads_child_id' => NULL
            // ],
            // [
            //     'id' => 49,
            //     'name' => '๑.๓ ๑๐๐,๐๐๐ - ๕๐๐,๐๐๐ บาท',
            //     'description' => NULL,
            //     'subworkload_id' => 9,
            //     'factor' => 6.00,
            //     'sort_order' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'is_child' => 0,
            //     'is_unique' => 1,
            //     'is_leader' => 1,
            //     'is_country' => 1,
            //     'list_subworkloads_child_id' => NULL
            // ],
            // [
            //     'id' => 50,
            //     'name' => '๑.๔ ๕๐๐,๐๐๐ - ๑,๐๐๐,๐๐๐ บาท',
            //     'description' => NULL,
            //     'subworkload_id' => 9,
            //     'factor' => 6.00,
            //     'sort_order' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'is_child' => 0,
            //     'is_unique' => 1,
            //     'is_leader' => 1,
            //     'is_country' => 1,
            //     'list_subworkloads_child_id' => NULL
            // ],
            // [
            //     'id' => 51,
            //     'name' => '๑.๕ ๑,๐๐๐,๐๐๐ - ๓,๐๐๐,๐๐๐ บาท',
            //     'description' => NULL,
            //     'subworkload_id' => 9,
            //     'factor' => 6.00,
            //     'sort_order' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'is_child' => 0,
            //     'is_unique' => 1,
            //     'is_leader' => 1,
            //     'is_country' => 1,
            //     'list_subworkloads_child_id' => NULL
            // ],
            // [
            //     'id' => 52,
            //     'name' => '๑.๖  มากกว่า ๓,๐๐๐,๐๐๐ บาท',
            //     'description' => NULL,
            //     'subworkload_id' => 9,
            //     'factor' => 6.00,
            //     'sort_order' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'is_child' => 0,
            //     'is_unique' => 1,
            //     'is_leader' => 1,
            //     'is_country' => 1,
            //     'list_subworkloads_child_id' => NULL
            // ],
            ////////////////////////////

            // 2.5 ในประเทศ + หัวหน้า 
            [
                'id' => 53,
                'name' => '๑. ไม่เกิน ๓ โครงการ',
                'description' => NULL,
                'subworkload_id' => 11,
                'factor' => 8.00,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 54,
                'name' => '๒. ๔ - ๖ โครงการย่อย',
                'description' => NULL,
                'subworkload_id' => 11,
                'factor' => 12.00,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 55,
                'name' => '๓. ๗ โครงการย่อยขึ้นไป',
                'description' => NULL,
                'subworkload_id' => 11,
                'factor' => 16.00,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],

            // // 2.5 ในประเทศ + ผู้ร่วม
            // [
            //     'id' => 56,
            //     'name' => '๑. ไม่เกิน ๓ โครงการ',
            //     'description' => NULL,
            //     'subworkload_id' => 11,
            //     'factor' => 2.00,
            //     'sort_order' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'is_child' => 0,
            //     'is_unique' => 1,
            //     'is_leader' => 0,
            //     'is_country' => 0,
            //     'list_subworkloads_child_id' => NULL
            // ],
            // [
            //     'id' => 57,
            //     'name' => '๒. ๔ - ๖ โครงการย่อย',
            //     'description' => NULL,
            //     'subworkload_id' => 11,
            //     'factor' => 2.00,
            //     'sort_order' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'is_child' => 0,
            //     'is_unique' => 1,
            //     'is_leader' => 0,
            //     'is_country' => 0,
            //     'list_subworkloads_child_id' => NULL
            // ],
            // [
            //     'id' => 58,
            //     'name' => '๓. ๗ โครงการย่อยขึ้นไป',
            //     'description' => NULL,
            //     'subworkload_id' => 11,
            //     'factor' => 2.00,
            //     'sort_order' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'is_child' => 0,
            //     'is_unique' => 1,
            //     'is_leader' => 0,
            //     'is_country' => 0,
            //     'list_subworkloads_child_id' => NULL
            // ],
            // 2.6 หัวหน้า
            [
                'id' => 59,
                'name' => '๑. โครงการวิจัยร่วมที่ดำเนินงานกับหน่วยงานภายนอกระดับชาติ',
                'description' => NULL,
                'subworkload_id' => 12,
                'factor' => 8.00,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 60,
                'name' => '๒. โครงการวิจัยร่วมที่ดำเนินงานกับหน่วยงานระดับนานาชาติ',
                'description' => NULL,
                'subworkload_id' => 12,
                'factor' => 16.00,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],

            // // 2.6 ผู้ร่วม
            // [
            //     'id' => 61,
            //     'name' => '๑. โครงการวิจัยร่วมที่ดำเนินงานกับหน่วยงานภายนอกระดับชาติ',
            //     'description' => NULL,
            //     'subworkload_id' => 12,
            //     'factor' => 4.00,
            //     'sort_order' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'is_child' => 0,
            //     'is_unique' => 1,
            //     'is_leader' => 0,
            //     'is_country' => 0,
            //     'list_subworkloads_child_id' => NULL
            // ],
            // [
            //     'id' => 62,
            //     'name' => '๒. โครงการวิจัยร่วมที่ดำเนินงานกับหน่วยงานระดับนานาชาติ',
            //     'description' => NULL,
            //     'subworkload_id' => 12,
            //     'factor' => 8.00,
            //     'sort_order' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'is_child' => 0,
            //     'is_unique' => 1,
            //     'is_leader' => 0,
            //     'is_country' => 0,
            //     'list_subworkloads_child_id' => NULL
            // ],

            // 2.7 หัวหน้า
            [
                'id' => 63,
                'name' => '๑. การเผยแพร่ผลงานสู่สารณะในลักษณะไดลักษณะหนึ่ง หนึ่ง หรือผ่าน สื่ออิเล็กทรอนิกส์ Online',
                'description' => NULL,
                'subworkload_id' => 13,
                'factor' => 2.00,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 64,
                'name' => '๒. ส่งรายงานการวิจัยฉบับสมบูรณ์ ฉบับบทความ',
                'description' => NULL,
                'subworkload_id' => 13,
                'factor' => 2,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 65,
                'name' => '๓. ส่งรายงานการวิจัยฉบับสมบูรณ์ เต็มรูปแบบ มีการเผยแพร่ตาม
เกณฑ์ ก.พ.อ.',
                'description' => NULL,
                'subworkload_id' => 13,
                'factor' => 4,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 66,
                'name' => '๔. ส่งรายงานการวิจัยฉบับสมบูรณ์ เต็มรูปแบบ มี ISBN',
                'description' => NULL,
                'subworkload_id' => 13,
                'factor' => 6,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 67,
                'name' => '๕. ตีพิมพ์ในวารสารทางวิชาการระดับชาติ ไม่อยู่ในฐานข้อมูล Tกai
Journal Citation Index (TCI)',
                'description' => NULL,
                'subworkload_id' => 13,
                'factor' => 2,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 68,
                'name' => '๖. ตีพิมพ์ในวารสารทางวิชาการะดับชาติ อยู่ในฐานข้อมูล Thai
Journal Citation Index (TCI)',
                'description' => NULL,
                'subworkload_id' => 13,
                'factor' => 8,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 69,
                'name' => '๗. ตีพิมพ์ผลงานวิชาการะดับนานาชาติที่ไม่อยู่ในฐานข้อมูลที่เป็น
ที่ยอมรับในระดับนานาชาติ',
                'description' => NULL,
                'subworkload_id' => 13,
                'factor' => 4,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 70,
                'name' => '๘. ตีพิมพ์ผลงานวิชาการะดับนานาชาติในฐานข้อมูลที่เป็นที่เป็นที่
ยอมรับในระดับนานาชาติ เช่น Scopus, ISI',
                'description' => NULL,
                'subworkload_id' => 13,
                'factor' => 16,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 71,
                'name' => '๙. นำเสนอผลงานในที่ประชุมวิชาการะดับชาติที่มีรายงานการประชุม
(Proceedings) เป็นไปตามเกณฑ์ ก.พ.อ.',
                'description' => NULL,
                'subworkload_id' => 13,
                'factor' => 4,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 72,
                'name' => '๑๐. นำเสนอผลงานในที่ประชุมวิชาการะดับนานาชาติที่ที่มีรายงานการ
ประชุม (Proceedings) เป็นไปตามเกณฑ์ ก.พ.อ.',
                'description' => NULL,
                'subworkload_id' => 13,
                'factor' => 6,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 73,
                'name' => '๑๑. ผลงานวิจัย หรือสิ่งประดิษธุ์ได้รับจดอนุสิทธิบัตร',
                'description' => NULL,
                'subworkload_id' => 13,
                'factor' => 14,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 74,
                'name' => '๑๒. ผลงานวิจัย หรือสิ่งประดิษฐ์ได้รับจดสิทธิบัตร',
                'description' => NULL,
                'subworkload_id' => 13,
                'factor' => 16,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 75,
                'name' => '๑๓. ผลงานวิจัย หรือสิ่งประดิษฐ์ได้รับจดสิทธิบัตร และนำไปใช้
ประโยชน์เชิงพาณิชย์',
                'description' => NULL,
                'subworkload_id' => 13,
                'factor' => 20,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 76,
                'name' => '๑๔. ผลงานวิจัย หรือสิ่งประดิษฐ์ที่ได้นำไปใช้ประโยชน์ต่อชุมชน
(เงื่อนไข ผู้ใช้มีหนังสือรับมอบและหนังสือรับรองผลการใช้งาน จำนวน
ไม่น้อยกว่า ๕ ราย)',
                'description' => NULL,
                'subworkload_id' => 13,
                'factor' => 10,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 77,
                'name' => '๑๕. ได้รับรางวัลผลงานวิจัย/สิ่งประดิษฐ์ระดับชาติ',
                'description' => NULL,
                'subworkload_id' => 13,
                'factor' => 10,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 78,
                'name' => '๑๖. ได้รับรางวัลผลงานวิจัย/สิ่งประดิษฐ์ระดับนานาชาติ',
                'description' => NULL,
                'subworkload_id' => 13,
                'factor' => 16,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 79,
                'name' => '๑๗. ได้รับรางวัลผลงานวิจัย/สิ่งประติษฐ์ ดีเด่นระดับชาติ',
                'description' => NULL,
                'subworkload_id' => 13,
                'factor' => 20,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 80,
                'name' => '๑๘. ได้รับรางวัลผลงานวิจัย/สิ่งประดิษฐ์ ดีเด่นระดับนานาชาติ',
                'description' => NULL,
                'subworkload_id' => 13,
                'factor' => 24,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 81,
                'name' => '๑๙. งานสร้างสรรค์ที่มีการเผยแพร่สู่สาธารณะในลักษณะใด
ลักษณะหนึ่ง หรือผ่านสื่ออิเล็กทรอนิกส์ Online',
                'description' => NULL,
                'subworkload_id' => 13,
                'factor' => 6,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 82,
                'name' => '๒๐. งานสร้างสรรค์ที่ได้รับการเผยแพรในระดับสถาบัน',
                'description' => NULL,
                'subworkload_id' => 13,
                'factor' => 8,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 83,
                'name' => '๒๑. งานสร้างสรรค์ที่ได้รับการเผยแพรในระดับชาติ',
                'description' => NULL,
                'subworkload_id' => 13,
                'factor' => 6,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 84,
                'name' => '๒๒. งานสร้างสรรค์ที่ได้รับการเผยแพรในระดับความร่วมมือ
ระหว่างประเทศ',
                'description' => NULL,
                'subworkload_id' => 13,
                'factor' => 8,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],

            //             // 2.7 ผู้ร่วม

            //             [
            //                 'id' => 85,
            //                 'name' => '๑. การเผยแพร่ผลงานสู่สารณะในลักษณะไดลักษณะหนึ่ง หนึ่ง หรือผ่าน สื่ออิเล็กทรอนิกส์ Online',
            //                 'description' => NULL,
            //                 'subworkload_id' => 13,
            //                 'factor' => 1.00,
            //                 'sort_order' => 1,
            //                 'created_at' => now(),
            //                 'updated_at' => now(),
            //                 'is_child' => 0,
            //                 'is_unique' => 1,
            //                 'is_leader' => 0,
            //                 'is_country' => 0,
            //                 'list_subworkloads_child_id' => NULL
            //             ],
            //             [
            //                 'id' => 86,
            //                 'name' => '๒. ส่งรายงานการวิจัยฉบับสมบูรณ์ ฉบับบทความ',
            //                 'description' => NULL,
            //                 'subworkload_id' => 13,
            //                 'factor' => 1,
            //                 'sort_order' => 1,
            //                 'created_at' => now(),
            //                 'updated_at' => now(),
            //                 'is_child' => 0,
            //                 'is_unique' => 1,
            //                 'is_leader' => 0,
            //                 'is_country' => 0,
            //                 'list_subworkloads_child_id' => NULL
            //             ],
            //             [
            //                 'id' => 87,
            //                 'name' => '๓. ส่งรายงานการวิจัยฉบับสมบูรณ์ เต็มรูปแบบ มีการเผยแพร่ตาม
            // เกณฑ์ ก.พ.อ.',
            //                 'description' => NULL,
            //                 'subworkload_id' => 13,
            //                 'factor' => 2,
            //                 'sort_order' => 1,
            //                 'created_at' => now(),
            //                 'updated_at' => now(),
            //                 'is_child' => 0,
            //                 'is_unique' => 1,
            //                 'is_leader' => 0,
            //                 'is_country' => 0,
            //                 'list_subworkloads_child_id' => NULL
            //             ],
            //             [
            //                 'id' => 88,
            //                 'name' => '๔. ส่งรายงานการวิจัยฉบับสมบูรณ์ เต็มรูปแบบ มี ISBN',
            //                 'description' => NULL,
            //                 'subworkload_id' => 13,
            //                 'factor' => 3,
            //                 'sort_order' => 1,
            //                 'created_at' => now(),
            //                 'updated_at' => now(),
            //                 'is_child' => 0,
            //                 'is_unique' => 1,
            //                 'is_leader' => 0,
            //                 'is_country' => 0,
            //                 'list_subworkloads_child_id' => NULL
            //             ],
            //             [
            //                 'id' => 89,
            //                 'name' => '๕. ตีพิมพ์ในวารสารทางวิชาการระดับชาติ ไม่อยู่ในฐานข้อมูล Tกai
            // Journal Citation Index (TCI)',
            //                 'description' => NULL,
            //                 'subworkload_id' => 13,
            //                 'factor' => 1,
            //                 'sort_order' => 1,
            //                 'created_at' => now(),
            //                 'updated_at' => now(),
            //                 'is_child' => 0,
            //                 'is_unique' => 1,
            //                 'is_leader' => 0,
            //                 'is_country' => 0,
            //                 'list_subworkloads_child_id' => NULL
            //             ],
            //             [
            //                 'id' => 90,
            //                 'name' => '๖. ตีพิมพ์ในวารสารทางวิชาการะดับชาติ อยู่ในฐานข้อมูล Thai
            // Journal Citation Index (TCI)',
            //                 'description' => NULL,
            //                 'subworkload_id' => 13,
            //                 'factor' => 4,
            //                 'sort_order' => 1,
            //                 'created_at' => now(),
            //                 'updated_at' => now(),
            //                 'is_child' => 0,
            //                 'is_unique' => 1,
            //                 'is_leader' => 0,
            //                 'is_country' => 0,
            //                 'list_subworkloads_child_id' => NULL
            //             ],
            //             [
            //                 'id' => 91,
            //                 'name' => '๗. ตีพิมพ์ผลงานวิชาการะดับนานาชาติที่ไม่อยู่ในฐานข้อมูลที่เป็น
            // ที่ยอมรับในระดับนานาชาติ',
            //                 'description' => NULL,
            //                 'subworkload_id' => 13,
            //                 'factor' => 2,
            //                 'sort_order' => 1,
            //                 'created_at' => now(),
            //                 'updated_at' => now(),
            //                 'is_child' => 0,
            //                 'is_unique' => 1,
            //                 'is_leader' => 0,
            //                 'is_country' => 0,
            //                 'list_subworkloads_child_id' => NULL
            //             ],
            //             [
            //                 'id' => 92,
            //                 'name' => '๘. ตีพิมพ์ผลงานวิชาการะดับนานาชาติในฐานข้อมูลที่เป็นที่เป็นที่
            // ยอมรับในระดับนานาชาติ เช่น Scopus, ISI',
            //                 'description' => NULL,
            //                 'subworkload_id' => 13,
            //                 'factor' => 8,
            //                 'sort_order' => 1,
            //                 'created_at' => now(),
            //                 'updated_at' => now(),
            //                 'is_child' => 0,
            //                 'is_unique' => 1,
            //                 'is_leader' => 0,
            //                 'is_country' => 0,
            //                 'list_subworkloads_child_id' => NULL
            //             ],
            //             [
            //                 'id' => 93,
            //                 'name' => '๙. นำเสนอผลงานในที่ประชุมวิชาการะดับชาติที่มีรายงานการประชุม
            // (Proceedings) เป็นไปตามเกณฑ์ ก.พ.อ.',
            //                 'description' => NULL,
            //                 'subworkload_id' => 13,
            //                 'factor' => 2,
            //                 'sort_order' => 1,
            //                 'created_at' => now(),
            //                 'updated_at' => now(),
            //                 'is_child' => 0,
            //                 'is_unique' => 1,
            //                 'is_leader' => 0,
            //                 'is_country' => 0,
            //                 'list_subworkloads_child_id' => NULL
            //             ],
            //             [
            //                 'id' => 94,
            //                 'name' => '๑๐. นำเสนอผลงานในที่ประชุมวิชาการะดับนานาชาติที่ที่มีรายงานการ
            // ประชุม (Proceedings) เป็นไปตามเกณฑ์ ก.พ.อ.',
            //                 'description' => NULL,
            //                 'subworkload_id' => 13,
            //                 'factor' => 3,
            //                 'sort_order' => 1,
            //                 'created_at' => now(),
            //                 'updated_at' => now(),
            //                 'is_child' => 0,
            //                 'is_unique' => 1,
            //                 'is_leader' => 0,
            //                 'is_country' => 0,
            //                 'list_subworkloads_child_id' => NULL
            //             ],
            //             [
            //                 'id' => 95,
            //                 'name' => '๑๑. ผลงานวิจัย หรือสิ่งประดิษธุ์ได้รับจดอนุสิทธิบัตร',
            //                 'description' => NULL,
            //                 'subworkload_id' => 13,
            //                 'factor' => 7,
            //                 'sort_order' => 1,
            //                 'created_at' => now(),
            //                 'updated_at' => now(),
            //                 'is_child' => 0,
            //                 'is_unique' => 1,
            //                 'is_leader' => 0,
            //                 'is_country' => 0,
            //                 'list_subworkloads_child_id' => NULL
            //             ],
            //             [
            //                 'id' => 96,
            //                 'name' => '๑๒. ผลงานวิจัย หรือสิ่งประดิษฐ์ได้รับจดสิทธิบัตร',
            //                 'description' => NULL,
            //                 'subworkload_id' => 13,
            //                 'factor' => 8,
            //                 'sort_order' => 1,
            //                 'created_at' => now(),
            //                 'updated_at' => now(),
            //                 'is_child' => 0,
            //                 'is_unique' => 1,
            //                 'is_leader' => 0,
            //                 'is_country' => 0,
            //                 'list_subworkloads_child_id' => NULL
            //             ],
            //             [
            //                 'id' => 97,
            //                 'name' => '๑๓. ผลงานวิจัย หรือสิ่งประดิษฐ์ได้รับจดสิทธิบัตร และนำไปใช้
            // ประโยชน์เชิงพาณิชย์',
            //                 'description' => NULL,
            //                 'subworkload_id' => 13,
            //                 'factor' => 10,
            //                 'sort_order' => 1,
            //                 'created_at' => now(),
            //                 'updated_at' => now(),
            //                 'is_child' => 0,
            //                 'is_unique' => 1,
            //                 'is_leader' => 0,
            //                 'is_country' => 0,
            //                 'list_subworkloads_child_id' => NULL
            //             ],
            //             [
            //                 'id' => 98,
            //                 'name' => '๑๔. ผลงานวิจัย หรือสิ่งประดิษฐ์ที่ได้นำไปใช้ประโยชน์ต่อชุมชน
            // (เงื่อนไข ผู้ใช้มีหนังสือรับมอบและหนังสือรับรองผลการใช้งาน จำนวน
            // ไม่น้อยกว่า ๕ ราย)',
            //                 'description' => NULL,
            //                 'subworkload_id' => 13,
            //                 'factor' => 5,
            //                 'sort_order' => 1,
            //                 'created_at' => now(),
            //                 'updated_at' => now(),
            //                 'is_child' => 0,
            //                 'is_unique' => 1,
            //                 'is_leader' => 0,
            //                 'is_country' => 0,
            //                 'list_subworkloads_child_id' => NULL
            //             ],
            //             [
            //                 'id' => 99,
            //                 'name' => '๑๕. ได้รับรางวัลผลงานวิจัย/สิ่งประดิษฐ์ระดับชาติ',
            //                 'description' => NULL,
            //                 'subworkload_id' => 13,
            //                 'factor' => 5,
            //                 'sort_order' => 1,
            //                 'created_at' => now(),
            //                 'updated_at' => now(),
            //                 'is_child' => 0,
            //                 'is_unique' => 1,
            //                 'is_leader' => 0,
            //                 'is_country' => 0,
            //                 'list_subworkloads_child_id' => NULL
            //             ],
            //             [
            //                 'id' => 100,
            //                 'name' => '๑๖. ได้รับรางวัลผลงานวิจัย/สิ่งประดิษฐ์ระดับนานาชาติ',
            //                 'description' => NULL,
            //                 'subworkload_id' => 13,
            //                 'factor' => 8,
            //                 'sort_order' => 1,
            //                 'created_at' => now(),
            //                 'updated_at' => now(),
            //                 'is_child' => 0,
            //                 'is_unique' => 1,
            //                 'is_leader' => 0,
            //                 'is_country' => 0,
            //                 'list_subworkloads_child_id' => NULL
            //             ],
            //             [
            //                 'id' => 101,
            //                 'name' => '๑๗. ได้รับรางวัลผลงานวิจัย/สิ่งประติษฐ์ ดีเด่นระดับชาติ',
            //                 'description' => NULL,
            //                 'subworkload_id' => 13,
            //                 'factor' => 10,
            //                 'sort_order' => 1,
            //                 'created_at' => now(),
            //                 'updated_at' => now(),
            //                 'is_child' => 0,
            //                 'is_unique' => 1,
            //                 'is_leader' => 0,
            //                 'is_country' => 0,
            //                 'list_subworkloads_child_id' => NULL
            //             ],
            //             [
            //                 'id' => 102,
            //                 'name' => '๑๘. ได้รับรางวัลผลงานวิจัย/สิ่งประดิษฐ์ ดีเด่นระดับนานาชาติ',
            //                 'description' => NULL,
            //                 'subworkload_id' => 13,
            //                 'factor' => 12,
            //                 'sort_order' => 1,
            //                 'created_at' => now(),
            //                 'updated_at' => now(),
            //                 'is_child' => 0,
            //                 'is_unique' => 1,
            //                 'is_leader' => 0,
            //                 'is_country' => 0,
            //                 'list_subworkloads_child_id' => NULL
            //             ],
            //             [
            //                 'id' => 103,
            //                 'name' => '๑๙. งานสร้างสรรค์ที่มีการเผยแพร่สู่สาธารณะในลักษณะใด
            // ลักษณะหนึ่ง หรือผ่านสื่ออิเล็กทรอนิกส์ Online',
            //                 'description' => NULL,
            //                 'subworkload_id' => 13,
            //                 'factor' => 3,
            //                 'sort_order' => 1,
            //                 'created_at' => now(),
            //                 'updated_at' => now(),
            //                 'is_child' => 0,
            //                 'is_unique' => 1,
            //                 'is_leader' => 0,
            //                 'is_country' => 0,
            //                 'list_subworkloads_child_id' => NULL
            //             ],
            //             [
            //                 'id' => 104,
            //                 'name' => '๒๐. งานสร้างสรรค์ที่ได้รับการเผยแพรในระดับสถาบัน',
            //                 'description' => NULL,
            //                 'subworkload_id' => 13,
            //                 'factor' => 4,
            //                 'sort_order' => 1,
            //                 'created_at' => now(),
            //                 'updated_at' => now(),
            //                 'is_child' => 0,
            //                 'is_unique' => 1,
            //                 'is_leader' => 0,
            //                 'is_country' => 0,
            //                 'list_subworkloads_child_id' => NULL
            //             ],
            //             [
            //                 'id' => 105,
            //                 'name' => '๒๑. งานสร้างสรรค์ที่ได้รับการเผยแพรในระดับชาติ',
            //                 'description' => NULL,
            //                 'subworkload_id' => 13,
            //                 'factor' => 3,
            //                 'sort_order' => 1,
            //                 'created_at' => now(),
            //                 'updated_at' => now(),
            //                 'is_child' => 0,
            //                 'is_unique' => 1,
            //                 'is_leader' => 0,
            //                 'is_country' => 0,
            //                 'list_subworkloads_child_id' => NULL
            //             ],
            //             [
            //                 'id' => 106,
            //                 'name' => '๒๒. งานสร้างสรรค์ที่ได้รับการเผยแพรในระดับความร่วมมือ
            // ระหว่างประเทศ',
            //                 'description' => NULL,
            //                 'subworkload_id' => 13,
            //                 'factor' => 4,
            //                 'sort_order' => 1,
            //                 'created_at' => now(),
            //                 'updated_at' => now(),
            //                 'is_child' => 0,
            //                 'is_unique' => 1,
            //                 'is_leader' => 0,
            //                 'is_country' => 0,
            //                 'list_subworkloads_child_id' => NULL
            //             ],

            // 3.1 

            [
                'id' => 107,
                'name' => '๑. เป็นอาจารย์พิเศษที่ไม่มีค่าตอบแทน',
                'description' => NULL,
                'subworkload_id' => 14,
                'factor' => 5,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 108,
                'name' => '๒. เป็นอาจารย์พิเศษที่มีค่าตอบแทน',
                'description' => NULL,
                'subworkload_id' => 14,
                'factor' => 1,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 109,
                'name' => '๓. เป็นวิทยากรบรรยายพิเศษ หน่วยงานภายใน',
                'description' => NULL,
                'subworkload_id' => 14,
                'factor' => 2,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 110,
                'name' => '๕. เป็นวิทยากรบรรยายพิเศษ หรือกรรมการ อื่น ๆ ของหน่วยงานภายนอก ระดับท้องถิ่น (ตำบล อำเภอ จังหวัด)',
                'description' => NULL,
                'subworkload_id' => 14,
                'factor' => 3,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 111,
                'name' => '๖. เป็นวิทยากรบรรยายพิเศษ หรือกรรมการ อื่น ๆ ของหน่วยงานภายนอก ระดับภูมิภาค',
                'description' => NULL,
                'subworkload_id' => 14,
                'factor' => 6,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 112,
                'name' => '๗. เป็นวิทยากรบรรยายพิเศษ หรือกรรมการ อื่น ๆ ของหน่วยงานภายนอก ระดับชาติ',
                'description' => NULL,
                'subworkload_id' => 14,
                'factor' => 9,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 113,
                'name' => '๗. เป็นวิทยากรบรรยายพิเศษ หรือกรรมการ อื่น ๆ ของหน่วยงานภายนอก ระดับนานาชาติ',
                'description' => NULL,
                'subworkload_id' => 14,
                'factor' => 12,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],

            // 3.2

            [
                'id' => 114,
                'name' => 'การจัดประชุม สัมมนาฝึกอบรมและจัดนิทรรศการ ๑ วัน',
                'description' => NULL,
                'subworkload_id' => 15,
                'factor' => 9,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 115,
                'name' => 'การจัดประชุม สัมมนาฝึกอบรมและจัดนิทรรศการ ๒ วัน',
                'description' => NULL,
                'subworkload_id' => 15,
                'factor' => 18,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 116,
                'name' => 'การจัดประชุม สัมมนาฝึกอบรมและจัดนิทรรศการ ตั้งแต่ ๓ วัน ขึ้นไป',
                'description' => NULL,
                'subworkload_id' => 15,
                'factor' => 27,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],

            // 3.3

            [
                'id' => 117,
                'name' => '๑. การเข้าร่วมประชุม สัมมนาฝึกอบรม และนิทรรศการ ๓-๓ วัน',
                'description' => NULL,
                'subworkload_id' => 16,
                'factor' => 1,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 118,
                'name' => '๒. การเข้าร่วมประชุม สัมมนาฝึกอบรมและนิทรรศการ ๔-๗ วัน',
                'description' => NULL,
                'subworkload_id' => 16,
                'factor' => 1.5,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 119,
                'name' => '๓. การเข้าร่วมประชุม สัมมนาฝึกอบรมและนิทรรศการ ๗ วันขึ้นไป',
                'description' => NULL,
                'subworkload_id' => 16,
                'factor' => 2,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],

            // 3.4

            [
                'id' => 120,
                'name' => '๑. ประธานที่ปรึกษาโครงการวิจัย/วิทยานิพนธ์ ที่ไม่มีค่าตอบแทน (ต่อเรื่อง)',
                'description' => NULL,
                'subworkload_id' => 17,
                'factor' => 4,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 121,
                'name' => '๒. กรรมการที่ปรึกษาโครงการวิจัย/วิทยานิพนธ์ ที่ไม่มีค่าตอบแทน (ต่อง)',
                'description' => NULL,
                'subworkload_id' => 17,
                'factor' => 2,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 122,
                'name' => '๓. ประธานที่ปรึกษาโครงการวิจัย/เมธีวิจัย ที่มีค่าตอบแทน (ต่อโครงการ)',
                'description' => NULL,
                'subworkload_id' => 17,
                'factor' => 2,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 123,
                'name' => '๔. กรรมการที่ปรึกษาโครงการวิจัย/เมธีวิจัย ที่มีค่าตอบแทน (ต่อโครงการ)',
                'description' => NULL,
                'subworkload_id' => 17,
                'factor' => 1,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 124,
                'name' => '๕. ที่ปรึกษาผลงานทางวิชาการ ประเภทวิชาชีพเฉพาะหรือเชี่ยวชาญเฉพาะ คศ.๓,
คศ.๔, ผศ., รศ.และ ศ. (ต่อคน)',
                'description' => NULL,
                'subworkload_id' => 17,
                'factor' => 2,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 125,
                'name' => '๖. กรรมการพิจารณาผลงานทางวิชาการประเภทวิชาชีพเอพาะหรือเชี่ยวชาญ
เฉพาะ คศ.๓, คศ.๔, ผศ., รศ.และ ศ. (ต่อคน)',
                'description' => NULL,
                'subworkload_id' => 17,
                'factor' => 4,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 126,
                'name' => '๗. พิจารณาบทความทางวิชาการ (Peer Review) หรืออ่านตำรา/หนังสือ ภายใน
และนอกมหาวิทยาลัยภาคภาษาไทย (ต่อเรื่อง)',
                'description' => NULL,
                'subworkload_id' => 17,
                'factor' => 2,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 127,
                'name' => '๘. พิจารณาบทความทางวิชาการ (Peer Review) หรืออ่านตำรา/หนังสือ ภายใน
และนอกมหาวิทยาลัยภาคภาษาต่างประเทศ (ต่อเรื่อง)',
                'description' => NULL,
                'subworkload_id' => 17,
                'factor' => 4,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 128,
                'name' => '๙. พิจารณารายงานการวิจัยฉบับสมบูรณ์ (ต่อเรื่อง)',
                'description' => NULL,
                'subworkload_id' => 17,
                'factor' => 1,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 129,
                'name' => '๑๐. พิจารณาข้อเสนอโครงการวิจัย (ต่อเรื่อง)',
                'description' => NULL,
                'subworkload_id' => 17,
                'factor' => 0.5,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 130,
                'name' => '๑๑. เป็นกองบรรณาธิการวารสารทางวิชาการ',
                'description' => NULL,
                'subworkload_id' => 17,
                'factor' => 0.5,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 131,
                'name' => '๑๒. เป็นบรรณาธิการวารสารทางวิชาการ',
                'description' => NULL,
                'subworkload_id' => 17,
                'factor' => 4,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 132,
                'name' => '๑๓. แปลเอกสารทางวิชาการเป็นภาษาต่างประเทศ (ต่อบทคัดย่อ)',
                'description' => NULL,
                'subworkload_id' => 17,
                'factor' => 0.2,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 133,
                'name' => '๑๔. แปลเอกสารทางวิชาการเป็นภาษาต่างประเทศ (ต่อบทความ)',
                'description' => NULL,
                'subworkload_id' => 17,
                'factor' => 1,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 134,
                'name' => '๑๕. ที่ปรึกษาหน่วยงานภาครัฐภายนอกมหาวิทยาลัย',
                'description' => NULL,
                'subworkload_id' => 17,
                'factor' => 4,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 135,
                'name' => '๑๖. คณะกรรมการดำเนินงานของหน่วยงานภาครัฐภายใน/ภายนอกมหาวิทยาลัย',
                'description' => NULL,
                'subworkload_id' => 17,
                'factor' => 2,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 136,
                'name' => '๑๗. เป็นคณะกรรมการกลั่นกรองผลงานวิชาการเบื้องต้น (ต่อเรื่องต่อคน)',
                'description' => NULL,
                'subworkload_id' => 17,
                'factor' => 0.5,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 137,
                'name' => '๑๘. บริการทางวิชาการให้คำปรึกษา วิเคราะห์ ตรวจสอบงานแก่ชุมชน ฯลฯ (ต่อเรื่อง,ต่อคน)',
                'description' => NULL,
                'subworkload_id' => 17,
                'factor' => 2,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 138,
                'name' => '๑๙. กรรมการประเมินผลการสอนเพื่อขอตำแหน่งทางวิชาการ',
                'description' => NULL,
                'subworkload_id' => 17,
                'factor' => 1,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 0,
                'is_leader' => 0,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],

            // 3.5 หัวหน้า

            [
                'id' => 139,
                'name' => '๑. รายได้ไม่ถึง ๑๐,๐๐๐ บาท',
                'description' => NULL,
                'subworkload_id' => 18,
                'factor' => 6,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 140,
                'name' => '๒. รายได้ ๑๐,๐๐๐ บาทขึ้นไปแต่ไม่ถึง ๕๐,๐๐๐ บาท',
                'description' => NULL,
                'subworkload_id' => 18,
                'factor' => 10,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 141,
                'name' => '๓. รายได้ ๕๐,๐๐๐ บาทขึ้นไปแต่ไม่ถึง ๑๐๐,๐๐๐ บาท',
                'description' => NULL,
                'subworkload_id' => 18,
                'factor' => 12,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 142,
                'name' => '๔. รายได้ ๑๐๐,๐๐๐ บาทขึ้นไปแต่ไม่ถึง ๕๐๐,๐๐๐ บาท',
                'description' => NULL,
                'subworkload_id' => 18,
                'factor' => 14,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 143,
                'name' => '๕. รายได้ ๕๐๐,๐๐๐ บาทขึ้นไปแต่ไม่ถึง ๑,๐๐๐,๐๐๐ บาท',
                'description' => NULL,
                'subworkload_id' => 18,
                'factor' => 16,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 144,
                'name' => '๖. รายได้ ๑,๐๐๐,๐๐๐ บาทขึ้นไปแต่ไม่ถึง ๓,๐๐๐,๐๐๐ บาท',
                'description' => NULL,
                'subworkload_id' => 18,
                'factor' => 20,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],
            [
                'id' => 145,
                'name' => '๗. รายได้ตั้งแต่ ๓,๐๐๐,๐๐๐ บาทขึ้นไป',
                'description' => NULL,
                'subworkload_id' => 18,
                'factor' => 24,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'is_child' => 0,
                'is_unique' => 1,
                'is_leader' => 1,
                'is_country' => 0,
                'list_subworkloads_child_id' => NULL
            ],

            

        ]);
    }
}
